build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker build -t nusa-exchange/frontend --build-arg NPM_TOKEN=${NPM_TOKEN} .
    - docker push nusa-exchange/frontend
